export type CountryCodeOption = {
  label: string;
  value: string;
};

export const STRONG_PASSWORD_REGEX =
  /^(?=.*[A-Za-z])(?=.*\d)(?=.*[^A-Za-z\d]).{8,}$/;

export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "10minutemail.com",
  "20minutemail.com",
  "dispostable.com",
  "fakeinbox.com",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.com",
  "maildrop.cc",
  "mailinator.com",
  "mailnesia.com",
  "mailpoof.com",
  "mohmal.com",
  "mytemp.email",
  "sharklasers.com",
  "tempmail.com",
  "tempmail.net",
  "tmpmail.org",
  "trashmail.com",
  "yopmail.com",
]);

export const TOP_100_COUNTRY_CODES: CountryCodeOption[] = [
  { label: "United States (+1)", value: "+1" },
  { label: "Canada (+1)", value: "+1" },
  { label: "India (+91)", value: "+91" },
  { label: "United Kingdom (+44)", value: "+44" },
  { label: "Australia (+61)", value: "+61" },
  { label: "Germany (+49)", value: "+49" },
  { label: "France (+33)", value: "+33" },
  { label: "Italy (+39)", value: "+39" },
  { label: "Spain (+34)", value: "+34" },
  { label: "Netherlands (+31)", value: "+31" },
  { label: "Belgium (+32)", value: "+32" },
  { label: "Switzerland (+41)", value: "+41" },
  { label: "Austria (+43)", value: "+43" },
  { label: "Ireland (+353)", value: "+353" },
  { label: "Sweden (+46)", value: "+46" },
  { label: "Norway (+47)", value: "+47" },
  { label: "Denmark (+45)", value: "+45" },
  { label: "Finland (+358)", value: "+358" },
  { label: "Poland (+48)", value: "+48" },
  { label: "Portugal (+351)", value: "+351" },
  { label: "Greece (+30)", value: "+30" },
  { label: "Czech Republic (+420)", value: "+420" },
  { label: "Hungary (+36)", value: "+36" },
  { label: "Romania (+40)", value: "+40" },
  { label: "Bulgaria (+359)", value: "+359" },
  { label: "Croatia (+385)", value: "+385" },
  { label: "Serbia (+381)", value: "+381" },
  { label: "Ukraine (+380)", value: "+380" },
  { label: "Russia (+7)", value: "+7" },
  { label: "Turkey (+90)", value: "+90" },
  { label: "United Arab Emirates (+971)", value: "+971" },
  { label: "Saudi Arabia (+966)", value: "+966" },
  { label: "Qatar (+974)", value: "+974" },
  { label: "Kuwait (+965)", value: "+965" },
  { label: "Bahrain (+973)", value: "+973" },
  { label: "Oman (+968)", value: "+968" },
  { label: "Israel (+972)", value: "+972" },
  { label: "Jordan (+962)", value: "+962" },
  { label: "Lebanon (+961)", value: "+961" },
  { label: "Egypt (+20)", value: "+20" },
  { label: "South Africa (+27)", value: "+27" },
  { label: "Nigeria (+234)", value: "+234" },
  { label: "Kenya (+254)", value: "+254" },
  { label: "Ghana (+233)", value: "+233" },
  { label: "Morocco (+212)", value: "+212" },
  { label: "Algeria (+213)", value: "+213" },
  { label: "Tunisia (+216)", value: "+216" },
  { label: "Ethiopia (+251)", value: "+251" },
  { label: "Tanzania (+255)", value: "+255" },
  { label: "Uganda (+256)", value: "+256" },
  { label: "China (+86)", value: "+86" },
  { label: "Japan (+81)", value: "+81" },
  { label: "South Korea (+82)", value: "+82" },
  { label: "Singapore (+65)", value: "+65" },
  { label: "Malaysia (+60)", value: "+60" },
  { label: "Indonesia (+62)", value: "+62" },
  { label: "Thailand (+66)", value: "+66" },
  { label: "Vietnam (+84)", value: "+84" },
  { label: "Philippines (+63)", value: "+63" },
  { label: "Bangladesh (+880)", value: "+880" },
  { label: "Pakistan (+92)", value: "+92" },
  { label: "Sri Lanka (+94)", value: "+94" },
  { label: "Nepal (+977)", value: "+977" },
  { label: "New Zealand (+64)", value: "+64" },
  { label: "Brazil (+55)", value: "+55" },
  { label: "Mexico (+52)", value: "+52" },
  { label: "Argentina (+54)", value: "+54" },
  { label: "Chile (+56)", value: "+56" },
  { label: "Colombia (+57)", value: "+57" },
  { label: "Peru (+51)", value: "+51" },
  { label: "Venezuela (+58)", value: "+58" },
  { label: "Ecuador (+593)", value: "+593" },
  { label: "Uruguay (+598)", value: "+598" },
  { label: "Paraguay (+595)", value: "+595" },
  { label: "Bolivia (+591)", value: "+591" },
  { label: "Costa Rica (+506)", value: "+506" },
  { label: "Panama (+507)", value: "+507" },
  { label: "Dominican Republic (+1)", value: "+1" },
  { label: "Jamaica (+1)", value: "+1" },
  { label: "Guatemala (+502)", value: "+502" },
  { label: "Honduras (+504)", value: "+504" },
  { label: "El Salvador (+503)", value: "+503" },
  { label: "Nicaragua (+505)", value: "+505" },
  { label: "Cuba (+53)", value: "+53" },
  { label: "Puerto Rico (+1)", value: "+1" },
  { label: "Iceland (+354)", value: "+354" },
  { label: "Luxembourg (+352)", value: "+352" },
  { label: "Slovakia (+421)", value: "+421" },
  { label: "Slovenia (+386)", value: "+386" },
  { label: "Lithuania (+370)", value: "+370" },
  { label: "Latvia (+371)", value: "+371" },
  { label: "Estonia (+372)", value: "+372" },
  { label: "Malta (+356)", value: "+356" },
  { label: "Cyprus (+357)", value: "+357" },
  { label: "Belarus (+375)", value: "+375" },
  { label: "Moldova (+373)", value: "+373" },
  { label: "Kazakhstan (+7)", value: "+7" },
  { label: "Uzbekistan (+998)", value: "+998" },
  { label: "Azerbaijan (+994)", value: "+994" },
  { label: "Georgia (+995)", value: "+995" },
  { label: "Armenia (+374)", value: "+374" },
  { label: "Cambodia (+855)", value: "+855" },
  { label: "Myanmar (+95)", value: "+95" },
  { label: "Laos (+856)", value: "+856" },
  { label: "Mongolia (+976)", value: "+976" },
];
